name: CD - Deploy Infrastructure to AWS

on:
  workflow_dispatch: # Permite acionamento manual

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=./engenharia-de-ia/Sistema\ de\ RAG\ em\ Larga\ Escala\ com\ Vector\ DB\ Gerenciado/terraform init

      - name: Terraform Apply
        run: |
          terraform -chdir=./engenharia-de-ia/Sistema\ de\ RAG\ em\ Larga\ Escala\ com\ Vector\ DB\ Gerenciado/terraform apply -auto-approve \
          -var="google_api_key=${{ secrets.GOOGLE_API_KEY }}" \
          -var="pinecone_api_key=${{ secrets.PINECONE_API_KEY }}" \
          -var="pinecone_host=${{ secrets.PINECONE_HOST }}"